//! Reclaiming derived audio, safely (#98).
//!
//! Every destructive edit writes a content-addressed WAV and nothing
//! ever deleted one. A five-minute stereo track is roughly 55 MB per
//! edit, so fifty edits is about 2.7 GB of files nobody will open
//! again, and a long project grows until the disk does.
//!
//! ## Why the obvious sweep frees nothing
//!
//! Mark-and-sweep over the DAG recovers zero bytes, because undo means
//! *every node is reachable by design*. That is the entire point of the
//! graph. Reachability is the wrong question here.
//!
//! ## The question that does work
//!
//! Not "is this file reachable?" but **"if I delete this, can I get it
//! back?"**
//!
//! The CAS name is a blake3 hash of the post-edit samples and the edits
//! are deterministic, so a file whose whole ancestor chain records a
//! reproducible op can be regenerated byte-identically from its parent.
//! That property does not hold in most caches, and it is what makes a
//! cap safe rather than lossy: sweeping such a file costs a re-render
//! on undo and nothing else.
//!
//! ## The rules
//!
//! 1. **Never touch a file the current head names.** Whatever the
//!    policy, the session you are looking at keeps working.
//! 2. **Never touch a file no op can rebuild.** A node written before
//!    provenance existed, or one whose chain has a non-reproducible
//!    link (an ML model's weights are not part of the session), records
//!    no way back. Absent provenance reads as "not rebuildable", which
//!    is the safe direction.
//! 3. **Orphans go first.** A file in `derived/` that *no* node names
//!    is unreachable for good: node states are immutable and
//!    content-addressed, so nothing can come to reference it later. It
//!    is the one category that is pure garbage rather than a cache,
//!    and it is freed before anything regenerable is touched. Audacity
//!    reaches the same conclusion from the other direction — its
//!    project check finds orphaned block files and offers to remove
//!    them.
//! 4. **Then oldest first.** Least-recently-used by mtime among the
//!    rebuildable, because the edit you undid five minutes ago is the
//!    one you are most likely to want back.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::provenance::derived_dir;

/// How much derived audio a project keeps before the history sweep runs:
/// 2 GiB, about 36 five-minute stereo edits of undo history kept on disk,
/// with anything older rebuilt when the user goes back to it (#98).
pub const DEFAULT_DERIVED_CAP_BYTES: u64 = 2 * 1024 * 1024 * 1024;

/// What a sweep did, in the terms the caller has to be able to report.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SweepReport {
    pub removed_files: usize,
    pub freed_bytes: u64,
    /// Bytes still in `derived/` afterwards.
    pub remaining_bytes: u64,
    /// Orphans freed — in `derived/` and named by no node at all.
    /// Counted separately because this is the only category that is
    /// genuinely gone rather than regenerable.
    pub removed_orphans: usize,
    /// Files that were over the cap but could not be touched, because
    /// the head names them or nothing records how to rebuild them.
    pub kept_unrebuildable: usize,
    /// Files whose history says they can be rebuilt, kept because a
    /// replay did not actually rebuild them (#356). Anything counted here
    /// is a gap between what provenance records and what replay does.
    pub kept_unverified: usize,
    /// Flattened lane copies (`track-<hash>.wav`) of clip lists only
    /// history holds. A cache: `list_tracks` writes one again from its
    /// clips' sources whenever the timeline shows that clip list.
    pub removed_lane_copies: usize,
}

fn key(path: &Path) -> PathBuf {
    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

/// Paths the current head needs — never swept, under any policy: the
/// audio its clips name, and the flattened lane copies the timeline is
/// showing for its tracks.
///
/// `None` when there is a head that cannot be read. Then nothing is
/// known to be safe, and the caller must not sweep at all.
fn head_refs(store: &session::Store) -> Option<BTreeSet<PathBuf>> {
    let mut out = BTreeSet::new();
    let Some(head) = store.head() else {
        return Some(out);
    };
    let node = store.get(head).ok()?;
    out.extend(all_refs(std::slice::from_ref(&node)));
    out.extend(lane_copies(
        store.project_dir(),
        std::slice::from_ref(&node),
    ));
    Some(out)
}

/// The flattened lane copy (`track-<hash>.wav`) of every non-empty clip
/// list these nodes hold.
///
/// No node names these files — they are a cache keyed by a track's clip
/// list — so a sweep that asked only which files nodes name would take
/// every one for an orphan, including the one the timeline is showing.
pub(crate) fn lane_copies(project_dir: &Path, nodes: &[session::SessionNode]) -> BTreeSet<PathBuf> {
    let mut out = BTreeSet::new();
    for node in nodes {
        for track in &node.state.tracks {
            if !track.clips.is_empty() {
                out.insert(key(&crate::flattened_track_path(project_dir, &track.clips)));
            }
        }
    }
    out
}

/// Paths named by any node at all.
///
/// The complement of this within `derived/` is orphans: unreachable for
/// good, since node states are immutable and content-addressed.
fn all_refs(nodes: &[session::SessionNode]) -> BTreeSet<PathBuf> {
    let mut out = BTreeSet::new();
    for node in nodes {
        for track in &node.state.tracks {
            for clip in &track.clips {
                out.insert(key(&clip.source_path));
            }
        }
    }
    out
}

/// Paths a replay could put back.
///
/// A node's audio is rebuildable when the node records a reproducible
/// op *and* every node between it and a root does too — replay starts
/// from a state that still exists, so one missing link upstream strands
/// everything below it.
pub fn rebuildable_paths(nodes: &[session::SessionNode]) -> BTreeSet<PathBuf> {
    let by_id: HashMap<_, _> = nodes.iter().map(|n| (n.id, n)).collect();
    let mut out = BTreeSet::new();

    for node in nodes {
        let mut cur = Some(node);
        let replayable = loop {
            let Some(n) = cur else { break true }; // reached a root
            match &n.op {
                Some(op) if op.reproducible => cur = n.parent.and_then(|p| by_id.get(&p).copied()),
                _ => break false,
            }
        };
        if replayable {
            for track in &node.state.tracks {
                for clip in &track.clips {
                    out.insert(key(&clip.source_path));
                }
            }
        }
    }
    out
}

/// Bring `derived/` under `cap_bytes`, deleting only what can be put
/// back: [`plan_sweep`], then [`apply_sweep`] on the same store.
///
/// Returns without touching anything when already under the cap, so
/// calling this often is cheap.
///
/// A file that older history names is deleted only once a replay has
/// rebuilt it (the `Verifier` below). Provenance alone said five kinds of
/// history could be rebuilt when they could not (#356); a sweep that
/// trusted it deleted audio for good. Every path that reads a node's
/// audio or moves the head to it rebuilds what this removed first
/// ([`crate::rederive::materialize`]), so a swept node still plays,
/// renders and exports.
pub fn sweep(store: &session::Store, cap_bytes: u64) -> std::io::Result<SweepReport> {
    let plan = plan_sweep(store, cap_bytes)?;
    apply_sweep(store, &plan)
}

/// What a sweep would delete, decided without deleting anything.
///
/// Deciding is the slow half — verifying history takes replays — and it
/// only reads. Deleting is quick, and is the half that has to agree with
/// the store as it is at that moment. Split, an app can plan on a store
/// handle of its own while edits go on, and apply under the lock its
/// edits take ([`apply_sweep`]), so no edit waits on a replay.
#[derive(Debug, Clone, Default)]
pub struct SweepPlan {
    project_dir: PathBuf,
    cap_bytes: u64,
    /// In the order to delete them.
    candidates: Vec<(PathBuf, Kind)>,
    kept_unrebuildable: usize,
    kept_unverified: usize,
}

impl SweepPlan {
    /// Nothing to delete: under the cap, or nothing over it may go.
    pub fn is_empty(&self) -> bool {
        self.candidates.is_empty()
    }

    /// The project this plan was made for.
    pub fn project_dir(&self) -> &Path {
        &self.project_dir
    }
}

/// Why a file may go, which decides what must still hold when it does.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Kind {
    /// Named by no node, and no lane copy of any clip list.
    Orphan,
    /// A lane copy of a clip list only history holds.
    LaneCopy,
    /// Named only by history, and a replay has rebuilt it.
    History,
}

/// Decide what to delete to bring `derived/` under `cap_bytes`, deleting
/// nothing. Orphans first, then lane copies of history's clip lists, then
/// history's audio a replay has rebuilt; oldest first within each.
pub fn plan_sweep(store: &session::Store, cap_bytes: u64) -> std::io::Result<SweepPlan> {
    let mut plan = SweepPlan {
        project_dir: store.project_dir().to_path_buf(),
        cap_bytes,
        ..Default::default()
    };
    let dir = derived_dir(store.project_dir());
    if !dir.is_dir() {
        return Ok(plan);
    }
    // Under the cap costs one directory listing, and nothing else: this
    // runs every minute an app is open.
    let (mut files, total) = list_files(&dir)?;
    if total <= cap_bytes {
        return Ok(plan);
    }

    // What names what is the whole basis for deleting anything. A store
    // whose nodes cannot all be read names nothing, and sweeping it would
    // take every file for an orphan — so it is left alone.
    let Ok(nodes) = store.list_nodes() else {
        return Ok(plan);
    };
    let Some(protected) = head_refs(store) else {
        return Ok(plan);
    };
    let referenced = all_refs(&nodes);
    let lanes = lane_copies(store.project_dir(), &nodes);
    let rebuildable = rebuildable_paths(&nodes);
    // Which nodes name each file, to replay one when the file's turn
    // comes.
    let mut naming: HashMap<PathBuf, Vec<session::NodeId>> = HashMap::new();
    for node in &nodes {
        for track in &node.state.tracks {
            for clip in &track.clips {
                naming
                    .entry(key(&clip.source_path))
                    .or_default()
                    .push(node.id);
            }
        }
    }
    let mut verifier = Verifier::new(&dir);

    // Pure garbage goes before anything somebody might want, and a lane
    // copy — rebuilt from its sources in one pass — before audio that
    // takes a replay to rebuild.
    let kind_of = |k: &PathBuf| {
        if referenced.contains(k) {
            Kind::History
        } else if lanes.contains(k) {
            Kind::LaneCopy
        } else {
            Kind::Orphan
        }
    };
    let rank = |kind: Kind| match kind {
        Kind::Orphan => 0,
        Kind::LaneCopy => 1,
        Kind::History => 2,
    };
    files.sort_by_key(|(path, _, mtime)| (rank(kind_of(&key(path))), *mtime));

    let mut remaining = total;
    for (path, bytes, _) in files {
        if remaining <= cap_bytes {
            break;
        }
        let k = key(&path);
        if protected.contains(&k) {
            continue;
        }
        let kind = kind_of(&k);
        if kind == Kind::History {
            if !rebuildable.contains(&k) {
                // A node names it but nothing records how to make it
                // again. Deleting this is the one thing that would lose
                // work, so it stays however far over the cap the
                // directory is — and it is counted, because a sweep that
                // cannot reach its target should say why rather than
                // look ineffective.
                plan.kept_unrebuildable += 1;
                continue;
            }
            if !verifier.rebuilds(store, &k, naming.get(&k).map(Vec::as_slice)) {
                // The record says it can come back; a replay says
                // otherwise. The replay is what `materialize` will run,
                // so it is the one to believe (#356).
                plan.kept_unverified += 1;
                continue;
            }
        }
        plan.candidates.push((path, kind));
        remaining -= bytes;
    }
    Ok(plan)
}

/// Delete what `plan` chose, as far as the store still agrees.
///
/// Run under the lock the store's edits take, so nothing changes while it
/// runs. Between planning and now the store may have: moved its head onto
/// a planned file, or come to name a file that was an orphan (an edit
/// whose output matched one byte for byte). Each file is checked against
/// the store as it is now, and one the head needs, or that has stopped
/// being what the plan took it for, stays. A plan for another project
/// deletes nothing.
pub fn apply_sweep(store: &session::Store, plan: &SweepPlan) -> std::io::Result<SweepReport> {
    let mut report = SweepReport {
        kept_unrebuildable: plan.kept_unrebuildable,
        kept_unverified: plan.kept_unverified,
        ..Default::default()
    };
    let dir = derived_dir(store.project_dir());
    if key(store.project_dir()) != key(&plan.project_dir) || !dir.is_dir() {
        return Ok(report);
    }
    let (_, total) = list_files(&dir)?;
    report.remaining_bytes = total;
    if plan.candidates.is_empty() || total <= plan.cap_bytes {
        return Ok(report);
    }

    let Ok(nodes) = store.list_nodes() else {
        return Ok(report);
    };
    let Some(protected) = head_refs(store) else {
        return Ok(report);
    };
    let referenced = all_refs(&nodes);
    let lanes = lane_copies(store.project_dir(), &nodes);

    for (path, kind) in &plan.candidates {
        if report.remaining_bytes <= plan.cap_bytes {
            break;
        }
        let k = key(path);
        if protected.contains(&k) {
            continue;
        }
        let still = match kind {
            Kind::Orphan => !referenced.contains(&k) && !lanes.contains(&k),
            // A clip naming it now would make it audio a replay has not
            // verified.
            Kind::LaneCopy => !referenced.contains(&k),
            // Verified by a replay; what names it since cannot change that.
            Kind::History => true,
        };
        if !still {
            continue;
        }
        let Ok(meta) = std::fs::metadata(path) else {
            continue;
        };
        if std::fs::remove_file(path).is_ok() {
            report.removed_files += 1;
            match kind {
                Kind::Orphan => report.removed_orphans += 1,
                Kind::LaneCopy => report.removed_lane_copies += 1,
                Kind::History => {}
            }
            report.freed_bytes += meta.len();
            report.remaining_bytes = report.remaining_bytes.saturating_sub(meta.len());
        }
    }
    Ok(report)
}

/// `(path, bytes, mtime)` for every file in `dir`, and their total size.
#[allow(clippy::type_complexity)]
fn list_files(dir: &Path) -> std::io::Result<(Vec<(PathBuf, u64, std::time::SystemTime)>, u64)> {
    let mut files = Vec::new();
    let mut total = 0u64;
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let meta = entry.metadata()?;
        let mtime = meta.modified().unwrap_or(std::time::UNIX_EPOCH);
        total += meta.len();
        files.push((path, meta.len(), mtime));
    }
    Ok((files, total))
}

/// Proof, before a delete, that a file can be put back (#356).
///
/// Provenance says a chain can be replayed; five kinds of history proved
/// that claim wrong — after compaction, after a paste, with a range taken
/// from the chat message, after `apply_diff`, and once the original source
/// has moved. Each looked rebuildable and was not. Rather than chase every
/// such gap in the record, the sweep asks the replay itself: it runs the
/// node's own step on its parent's audio in a scratch project — exactly
/// the step a rebuild runs (`rederive`) — and a file is verified only if
/// the replay wrote a file of the same name: the same bytes, since names
/// are content hashes.
///
/// Each node is replayed at most once, and each replay is one step, so a
/// sweep costs about one edit's work per file it verifies. That is why
/// this runs only when the directory is over its cap.
struct Verifier {
    dir: PathBuf,
    verified: BTreeSet<PathBuf>,
    replayed: HashSet<session::NodeId>,
}

impl Verifier {
    fn new(dir: &Path) -> Self {
        Self {
            dir: dir.to_path_buf(),
            verified: BTreeSet::new(),
            replayed: HashSet::new(),
        }
    }

    /// Whether a replay of one of `nodes` rebuilds the file at `k`.
    fn rebuilds(
        &mut self,
        store: &session::Store,
        k: &Path,
        nodes: Option<&[session::NodeId]>,
    ) -> bool {
        for &id in nodes.unwrap_or_default() {
            if self.verified.contains(k) {
                break;
            }
            if !self.replayed.insert(id) {
                continue;
            }
            if let Ok(replay) = crate::rederive::replay(store, id) {
                for name in replay.produced() {
                    self.verified.insert(key(&self.dir.join(name)));
                }
            }
        }
        self.verified.contains(k)
    }
}

/// Remove every file in `derived/` that no node names — and nothing else.
///
/// The one reclamation that is safe without a replay: node states are
/// immutable and content-addressed, so a file no node names now can never
/// come to be named later. They come from edits that failed after writing
/// their output, from compaction, and from flattened track copies of clip
/// lists that no node has any more.
///
/// Flattened copies (`track-<hash>.wav`) are named by no node directly —
/// they are a cache keyed by a track's clip list — so every node's clip
/// lists count as naming theirs. Otherwise every flattened copy would be
/// taken for an orphan, including the one the timeline is showing.
///
/// Not the history sweep. [`sweep`] also removes audio only older nodes
/// name, once a replay has rebuilt it; review of #98 proved that record
/// alone was not enough for five kinds of history (after
/// `compact_session`, after a paste, a range taken from the chat message,
/// `apply_diff`, and a moved source file), which is why [`sweep`] now
/// verifies each file by replaying it before deleting it.
pub fn sweep_orphans(store: &session::Store) -> std::io::Result<SweepReport> {
    let dir = derived_dir(store.project_dir());
    if !dir.is_dir() {
        return Ok(SweepReport::default());
    }

    // A store whose nodes could not be read names nothing, and sweeping it
    // would empty the directory. Only a store that really has no history
    // may have everything in `derived/` counted as unnamed — and a head
    // with no nodes behind it is not that.
    let Ok(nodes) = store.list_nodes() else {
        return Ok(SweepReport::default());
    };
    if nodes.is_empty() && store.head().is_some() {
        return Ok(SweepReport::default());
    }
    let mut named = all_refs(&nodes);
    named.extend(lane_copies(store.project_dir(), &nodes));

    let mut report = SweepReport::default();
    for entry in std::fs::read_dir(&dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let bytes = entry.metadata()?.len();
        if named.contains(&key(&path)) {
            report.remaining_bytes += bytes;
            continue;
        }
        if std::fs::remove_file(&path).is_ok() {
            report.removed_files += 1;
            report.removed_orphans += 1;
            report.freed_bytes += bytes;
        } else {
            report.remaining_bytes += bytes;
        }
    }
    Ok(report)
}

// =============================================================================
// Compaction — trading history for disk, deliberately (#98 option b)
// =============================================================================

/// What a compaction would remove, computed before anything is touched
/// so the tool can describe it and then do exactly that.
#[derive(Debug, Clone, Default)]
pub struct CompactionPlan {
    /// Nodes to delete, in an order safe to apply: never a node that
    /// something still kept parents off.
    pub nodes: Vec<session::NodeId>,
    /// The oldest node that survives on the head's chain. Its parent
    /// link is cut when the plan is applied, so the kept history ends
    /// cleanly instead of pointing at something deleted.
    pub new_root: Option<session::NodeId>,
    /// Files only those nodes reference, and their total size.
    pub files: Vec<PathBuf>,
    pub bytes: u64,
    pub total_nodes: usize,
}

/// What a compaction actually did.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CompactionReport {
    pub removed_nodes: usize,
    pub removed_files: usize,
    pub freed_bytes: u64,
}

/// The head's chain, newest first.
fn chain_from(store: &session::Store, head: session::NodeId) -> Vec<session::NodeId> {
    let mut out = Vec::new();
    let mut cursor = Some(head);
    while let Some(id) = cursor {
        let Ok(node) = store.get(id) else { break };
        out.push(id);
        cursor = node.parent;
    }
    out
}

/// Work out what a compaction would remove.
///
/// Two things go: the tail of the head's chain beyond `keep_last`, and
/// anything not on the chain at all — branches forked away from and
/// never returned to.
///
/// The tail is kept *contiguous*. Removing a node from the middle of
/// the chain would strand everything below it, because a walk from the
/// head follows parent links and stops at the first gap. So the cut is
/// always "everything older than the Nth", never a set of individually
/// chosen nodes.
pub fn plan_compaction(
    store: &session::Store,
    head: session::NodeId,
    keep_last: usize,
) -> Result<CompactionPlan, String> {
    let all = store
        .list_nodes()
        .map_err(|e| format!("failed to list nodes: {e}"))?;
    let chain = chain_from(store, head);
    let chain_set: HashSet<_> = chain.iter().copied().collect();

    let mut doomed: Vec<session::NodeId> = Vec::new();
    let mut new_root = None;
    // The tail of the chain, oldest first so removal never orphans a
    // node that is still kept.
    if chain.len() > keep_last {
        doomed.extend(chain[keep_last..].iter().rev().copied());
        // The last one kept becomes a root; without this its parent
        // link dangles and walking back reads as a corrupt store.
        new_root = chain.get(keep_last - 1).copied();
    }
    // Everything off the chain entirely.
    for node in &all {
        if !chain_set.contains(&node.id) {
            doomed.push(node.id);
        }
    }

    // Which files survive: named by any node that is *not* being
    // removed. A file is only reclaimable when nothing kept wants it.
    let doomed_set: HashSet<_> = doomed.iter().copied().collect();
    let mut kept_refs: BTreeSet<PathBuf> = BTreeSet::new();
    let mut doomed_refs: BTreeSet<PathBuf> = BTreeSet::new();
    for node in &all {
        let target = if doomed_set.contains(&node.id) {
            &mut doomed_refs
        } else {
            &mut kept_refs
        };
        for track in &node.state.tracks {
            for clip in &track.clips {
                target.insert(key(&clip.source_path));
            }
        }
    }

    let mut files = Vec::new();
    let mut bytes = 0u64;
    for path in doomed_refs.difference(&kept_refs) {
        if let Ok(meta) = std::fs::metadata(path) {
            bytes += meta.len();
            files.push(path.clone());
        }
    }

    Ok(CompactionPlan {
        nodes: doomed,
        new_root,
        files,
        bytes,
        total_nodes: all.len(),
    })
}

/// Carry out a plan.
///
/// Nodes first, audio second. A compaction interrupted between the two
/// leaves a session whose history is shorter and whose audio is intact
/// — which still works. The other order would leave nodes pointing at
/// files that are gone.
pub fn apply_compaction(
    store: &mut session::Store,
    plan: &CompactionPlan,
) -> Result<CompactionReport, String> {
    let mut report = CompactionReport::default();

    for id in &plan.nodes {
        match store.remove_node(*id) {
            Ok(true) => report.removed_nodes += 1,
            Ok(false) => {}
            Err(e) => return Err(format!("failed to remove node {}: {e}", id.to_hex())),
        }
    }

    // Cut the dangling link before the audio goes, so an interruption
    // still leaves a walkable chain.
    if let Some(root) = plan.new_root {
        store
            .detach_parent(root)
            .map_err(|e| format!("failed to make {} a root: {e}", root.to_hex()))?;
    }

    for path in &plan.files {
        if let Ok(meta) = std::fs::metadata(path) {
            if std::fs::remove_file(path).is_ok() {
                report.removed_files += 1;
                report.freed_bytes += meta.len();
            }
        }
    }

    Ok(report)
}
