//! Reclaiming derived audio, safely (#98).
//!
//! Every destructive edit writes a content-addressed WAV and nothing
//! ever deleted one. A five-minute stereo track is roughly 55 MB per
//! edit, so fifty edits is about 2.7 GB of files nobody will open
//! again, and a long project grows until the disk does.
//!
//! ## Why the obvious sweep frees nothing
//!
//! Mark-and-sweep over the DAG recovers zero bytes, because undo means
//! *every node is reachable by design*. That is the entire point of the
//! graph. Reachability is the wrong question here.
//!
//! ## The question that does work
//!
//! Not "is this file reachable?" but **"if I delete this, can I get it
//! back?"**
//!
//! The CAS name is a blake3 hash of the post-edit samples and the edits
//! are deterministic, so a file whose whole ancestor chain records a
//! reproducible op can be regenerated byte-identically from its parent.
//! That property does not hold in most caches, and it is what makes a
//! cap safe rather than lossy: sweeping such a file costs a re-render
//! on undo and nothing else.
//!
//! ## The rules
//!
//! 1. **Never touch a file the current head names.** Whatever the
//!    policy, the session you are looking at keeps working.
//! 2. **Never touch a file no op can rebuild.** A node written before
//!    provenance existed, or one whose chain has a non-reproducible
//!    link (an ML model's weights are not part of the session), records
//!    no way back. Absent provenance reads as "not rebuildable", which
//!    is the safe direction.
//! 3. **Orphans go first.** A file in `derived/` that *no* node names
//!    is unreachable for good: node states are immutable and
//!    content-addressed, so nothing can come to reference it later. It
//!    is the one category that is pure garbage rather than a cache,
//!    and it is freed before anything regenerable is touched. Audacity
//!    reaches the same conclusion from the other direction — its
//!    project check finds orphaned block files and offers to remove
//!    them.
//! 4. **Then oldest first.** Least-recently-used by mtime among the
//!    rebuildable, because the edit you undid five minutes ago is the
//!    one you are most likely to want back.

use std::collections::{BTreeSet, HashMap, HashSet};
use std::path::{Path, PathBuf};

use crate::provenance::derived_dir;

/// What a sweep did, in the terms the caller has to be able to report.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct SweepReport {
    pub removed_files: usize,
    pub freed_bytes: u64,
    /// Bytes still in `derived/` afterwards.
    pub remaining_bytes: u64,
    /// Orphans freed — in `derived/` and named by no node at all.
    /// Counted separately because this is the only category that is
    /// genuinely gone rather than regenerable.
    pub removed_orphans: usize,
    /// Files that were over the cap but could not be touched, because
    /// the head names them or nothing records how to rebuild them.
    pub kept_unrebuildable: usize,
}

fn key(path: &Path) -> PathBuf {
    std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf())
}

/// Paths named by the current head — never swept, under any policy.
fn head_refs(store: &session::Store) -> BTreeSet<PathBuf> {
    let mut out = BTreeSet::new();
    let Some(head) = store.head() else {
        return out;
    };
    let Ok(node) = store.get(head) else {
        return out;
    };
    for track in &node.state.tracks {
        for clip in &track.clips {
            out.insert(key(&clip.source_path));
        }
    }
    out
}

/// Paths named by any node at all.
///
/// The complement of this within `derived/` is orphans: unreachable for
/// good, since node states are immutable and content-addressed.
fn all_refs(nodes: &[session::SessionNode]) -> BTreeSet<PathBuf> {
    let mut out = BTreeSet::new();
    for node in nodes {
        for track in &node.state.tracks {
            for clip in &track.clips {
                out.insert(key(&clip.source_path));
            }
        }
    }
    out
}

/// Paths a replay could put back.
///
/// A node's audio is rebuildable when the node records a reproducible
/// op *and* every node between it and a root does too — replay starts
/// from a state that still exists, so one missing link upstream strands
/// everything below it.
pub fn rebuildable_paths(nodes: &[session::SessionNode]) -> BTreeSet<PathBuf> {
    let by_id: HashMap<_, _> = nodes.iter().map(|n| (n.id, n)).collect();
    let mut out = BTreeSet::new();

    for node in nodes {
        let mut cur = Some(node);
        let replayable = loop {
            let Some(n) = cur else { break true }; // reached a root
            match &n.op {
                Some(op) if op.reproducible => cur = n.parent.and_then(|p| by_id.get(&p).copied()),
                _ => break false,
            }
        };
        if replayable {
            for track in &node.state.tracks {
                for clip in &track.clips {
                    out.insert(key(&clip.source_path));
                }
            }
        }
    }
    out
}

/// Bring `derived/` under `cap_bytes`, deleting only what can be put
/// back.
///
/// Returns without touching anything when already under the cap, so
/// calling this after every edit is cheap.
pub fn sweep(store: &session::Store, cap_bytes: u64) -> std::io::Result<SweepReport> {
    let dir = derived_dir(store.project_dir());
    if !dir.is_dir() {
        return Ok(SweepReport::default());
    }

    let nodes = store.list_nodes().unwrap_or_default();
    let protected = head_refs(store);
    let referenced = all_refs(&nodes);
    let rebuildable = rebuildable_paths(&nodes);

    // (path, bytes, mtime) for everything in the directory.
    let mut files: Vec<(PathBuf, u64, std::time::SystemTime)> = Vec::new();
    let mut total = 0u64;
    for entry in std::fs::read_dir(&dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let meta = entry.metadata()?;
        let mtime = meta.modified().unwrap_or(std::time::UNIX_EPOCH);
        total += meta.len();
        files.push((path, meta.len(), mtime));
    }

    if total <= cap_bytes {
        return Ok(SweepReport {
            remaining_bytes: total,
            ..Default::default()
        });
    }

    // Orphans first, then oldest. Sorting by (is-not-orphan, mtime)
    // puts pure garbage at the front of the queue, so a sweep frees the
    // bytes nobody can ever want before it touches a cache entry
    // somebody might.
    files.sort_by_key(|(path, _, mtime)| (referenced.contains(&key(path)), *mtime));

    let mut report = SweepReport::default();
    let mut remaining = total;

    for (path, bytes, _) in &files {
        if remaining <= cap_bytes {
            break;
        }
        let k = key(path);
        if protected.contains(&k) {
            continue;
        }
        let orphan = !referenced.contains(&k);
        if !orphan && !rebuildable.contains(&k) {
            // A node names it but nothing records how to make it again.
            // Deleting this is the one thing that would lose work, so
            // it stays however far over the cap the directory is — and
            // it is counted, because a sweep that cannot reach its
            // target should say why rather than look ineffective.
            report.kept_unrebuildable += 1;
            continue;
        }
        if std::fs::remove_file(path).is_ok() {
            report.removed_files += 1;
            if orphan {
                report.removed_orphans += 1;
            }
            report.freed_bytes += bytes;
            remaining -= bytes;
        }
    }

    report.remaining_bytes = remaining;
    Ok(report)
}

// =============================================================================
// Compaction — trading history for disk, deliberately (#98 option b)
// =============================================================================

/// What a compaction would remove, computed before anything is touched
/// so the tool can describe it and then do exactly that.
#[derive(Debug, Clone, Default)]
pub struct CompactionPlan {
    /// Nodes to delete, in an order safe to apply: never a node that
    /// something still kept parents off.
    pub nodes: Vec<session::NodeId>,
    /// The oldest node that survives on the head's chain. Its parent
    /// link is cut when the plan is applied, so the kept history ends
    /// cleanly instead of pointing at something deleted.
    pub new_root: Option<session::NodeId>,
    /// Files only those nodes reference, and their total size.
    pub files: Vec<PathBuf>,
    pub bytes: u64,
    pub total_nodes: usize,
}

/// What a compaction actually did.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CompactionReport {
    pub removed_nodes: usize,
    pub removed_files: usize,
    pub freed_bytes: u64,
}

/// The head's chain, newest first.
fn chain_from(store: &session::Store, head: session::NodeId) -> Vec<session::NodeId> {
    let mut out = Vec::new();
    let mut cursor = Some(head);
    while let Some(id) = cursor {
        let Ok(node) = store.get(id) else { break };
        out.push(id);
        cursor = node.parent;
    }
    out
}

/// Work out what a compaction would remove.
///
/// Two things go: the tail of the head's chain beyond `keep_last`, and
/// anything not on the chain at all — branches forked away from and
/// never returned to.
///
/// The tail is kept *contiguous*. Removing a node from the middle of
/// the chain would strand everything below it, because a walk from the
/// head follows parent links and stops at the first gap. So the cut is
/// always "everything older than the Nth", never a set of individually
/// chosen nodes.
pub fn plan_compaction(
    store: &session::Store,
    head: session::NodeId,
    keep_last: usize,
) -> Result<CompactionPlan, String> {
    let all = store
        .list_nodes()
        .map_err(|e| format!("failed to list nodes: {e}"))?;
    let chain = chain_from(store, head);
    let chain_set: HashSet<_> = chain.iter().copied().collect();

    let mut doomed: Vec<session::NodeId> = Vec::new();
    let mut new_root = None;
    // The tail of the chain, oldest first so removal never orphans a
    // node that is still kept.
    if chain.len() > keep_last {
        doomed.extend(chain[keep_last..].iter().rev().copied());
        // The last one kept becomes a root; without this its parent
        // link dangles and walking back reads as a corrupt store.
        new_root = chain.get(keep_last - 1).copied();
    }
    // Everything off the chain entirely.
    for node in &all {
        if !chain_set.contains(&node.id) {
            doomed.push(node.id);
        }
    }

    // Which files survive: named by any node that is *not* being
    // removed. A file is only reclaimable when nothing kept wants it.
    let doomed_set: HashSet<_> = doomed.iter().copied().collect();
    let mut kept_refs: BTreeSet<PathBuf> = BTreeSet::new();
    let mut doomed_refs: BTreeSet<PathBuf> = BTreeSet::new();
    for node in &all {
        let target = if doomed_set.contains(&node.id) {
            &mut doomed_refs
        } else {
            &mut kept_refs
        };
        for track in &node.state.tracks {
            for clip in &track.clips {
                target.insert(key(&clip.source_path));
            }
        }
    }

    let mut files = Vec::new();
    let mut bytes = 0u64;
    for path in doomed_refs.difference(&kept_refs) {
        if let Ok(meta) = std::fs::metadata(path) {
            bytes += meta.len();
            files.push(path.clone());
        }
    }

    Ok(CompactionPlan {
        nodes: doomed,
        new_root,
        files,
        bytes,
        total_nodes: all.len(),
    })
}

/// Carry out a plan.
///
/// Nodes first, audio second. A compaction interrupted between the two
/// leaves a session whose history is shorter and whose audio is intact
/// — which still works. The other order would leave nodes pointing at
/// files that are gone.
pub fn apply_compaction(
    store: &mut session::Store,
    plan: &CompactionPlan,
) -> Result<CompactionReport, String> {
    let mut report = CompactionReport::default();

    for id in &plan.nodes {
        match store.remove_node(*id) {
            Ok(true) => report.removed_nodes += 1,
            Ok(false) => {}
            Err(e) => return Err(format!("failed to remove node {}: {e}", id.to_hex())),
        }
    }

    // Cut the dangling link before the audio goes, so an interruption
    // still leaves a walkable chain.
    if let Some(root) = plan.new_root {
        store
            .detach_parent(root)
            .map_err(|e| format!("failed to make {} a root: {e}", root.to_hex()))?;
    }

    for path in &plan.files {
        if let Ok(meta) = std::fs::metadata(path) {
            if std::fs::remove_file(path).is_ok() {
                report.removed_files += 1;
                report.freed_bytes += meta.len();
            }
        }
    }

    Ok(report)
}
